<fieldset class="form">
	<legend>欢迎!</legend>
	<section style="padding: 3px 15px 5px 15px;">
		<table>
			<tr>
				<td style="width: 140px;">
					<img src="<?php echo $contextPath; ?>styles/images/desktop_icon.png" alt="Home" style="height: 128px; width: 128px; border: 0;" />
				</td>
				<td>
					<p>
						<?php echo htmlspecialchars($SESSION->get('userInfo')->name); ?>&nbsp;
						<span style="color: #999;">[ID=<?php echo htmlspecialchars($SESSION->get('userInfo')->id); ?>]</span>&nbsp;
						你好, 欢迎您的登录.
					</p>
					<p>本次登录IP: <?php echo htmlspecialchars($REQUEST->getIpAddress()); ?></p>
					<p>上次登录时间: <?php echo htmlspecialchars(date("Y-m-d H:i:s", $SESSION->get('userInfo')->last_login_time)); ?></p>
				</td>
			</tr>
		</table>
	</section>
</fieldset>
<fieldset class="form">
	<legend>待办任务</legend>
	<section style="padding: 0 15px 5px 15px;">
		<p>您有以下任务等待处理, 请点击左侧"待办任务"查看.</p>
		<div style="background-color: #FFF">
			<table class="easyui-datagrid" style="height: 200px;" rownumbers="true" singleSelect="true" url="<?php echo get_url('Task', 'getList', array('type' => 'todo'));?>">
				<thead>
					<tr>
						<th field="id" width="50">任务ID</th>
						<th field="creator_name" width="100">创建者</th>
						<th field="title" width="240">任务标题</th>
						<th field="process_name" width="100">流程模板</th>
						<th field="current_node_name" width="120">当前环节</th>
					</tr>
				</thead>
			</table>
		</div>
	</section>
</fieldset>
<fieldset class="form">
	<legend>系统信息</legend>
	<section style="padding: 0 15px 0 15px;">
		<table class="info-table">
			<tr>
				<td style="width: 220px;">作者:</td>
				<td>刘思贤(starlight36)</td>
			</tr>
			<tr>
				<td>主页:</td>
				<td><a href="http://starlight36.com" target="_blank">http://starlight36.com</a></td>
			</tr>
			<tr>
				<td>使用许可:</td>
				<td><a href="http://www.opensource.org/licenses/lgpl-3.0.html" target="_blank">LGPL v3.0</a></td>
			</tr>
		</table>
	</section>
</fieldset>